package id.rettorio.luxmarket.ui.theme

import androidx.compose.ui.graphics.Color

val saleAccent = Color(0xFFFA254C)
val primaryLight = Color(0xFF101317)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF2F3237)
val onPrimaryContainerLight = Color(0xFFBEC0C7)
val secondaryLight = Color(0xFF4A5157)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFF6E757C)
val onSecondaryContainerLight = Color(0xFFFFFFFF)
val tertiaryLight = Color(0xFF5A5F63)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFB9BEC2)
val onTertiaryContainerLight = Color(0xFF2B3034)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFCF8F8)
val onBackgroundLight = Color(0xFF1C1B1C)
val surfaceLight = Color(0xFFFBFCF8)
val onSurfaceLight = Color(0xFF1C1B1C)
val surfaceVariantLight = Color(0xFFE2E2E7)
val onSurfaceVariantLight = Color(0xFF45474B)
val outlineLight = Color(0xFF76777B)
val outlineVariantLight = Color(0xFFC6C6CB)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF313030)
val inverseOnSurfaceLight = Color(0xFFF3F0F0)
val inversePrimaryLight = Color(0xFFC4C6CD)
val surfaceDimLight = Color(0xFFDCD9D9)
val surfaceBrightLight = Color(0xFFFCF8F8)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF6F3F3)
val surfaceContainerLight = Color(0xFFF1EDED)
val surfaceContainerHighLight = Color(0xFFEBE7E7)
val surfaceContainerHighestLight = Color(0xFFE5E2E2)